import { jsPDF } from "jspdf";

/**
 * Export text content as a PDF file.
 * Uses jsPDF for lightweight client-side generation.
 */
export function exportAsPDF(text: string, filename = "axiom-export") {
  const doc = new jsPDF({ unit: "mm", format: "a4" });

  const margin = 20;
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const maxLineWidth = pageWidth - margin * 2;
  const lineHeight = 6;
  const headerHeight = 30;

  // Header
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("Axiom", margin, margin);
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(120);
  doc.text(
    `axiom-solver.com · ${new Date().toLocaleDateString()}`,
    margin,
    margin + 6
  );
  doc.setTextColor(0);

  // Separator line
  doc.setDrawColor(200);
  doc.line(margin, headerHeight, pageWidth - margin, headerHeight);

  // Body
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");

  const lines = doc.splitTextToSize(text, maxLineWidth);
  let y = headerHeight + 8;

  for (const line of lines) {
    if (y + lineHeight > pageHeight - margin) {
      doc.addPage();
      y = margin;
    }
    doc.text(line, margin, y);
    y += lineHeight;
  }

  // Footer on every page
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(
      `Generated by Axiom — Page ${i}/${totalPages}`,
      pageWidth / 2,
      pageHeight - 10,
      { align: "center" }
    );
  }

  doc.save(`${filename}.pdf`);
}

/**
 * Export text content as a DOCX file.
 * Uses a simple HTML approach with blob download for DOCX-compatible format.
 */
export function exportAsDOCX(text: string, filename = "axiom-export") {
  // Create a Word-compatible HTML document
  const htmlContent = `
    <html xmlns:o="urn:schemas-microsoft-com:office:office"
          xmlns:w="urn:schemas-microsoft-com:office:word"
          xmlns="http://www.w3.org/TR/REC-html40">
    <head>
      <meta charset="utf-8">
      <style>
        body { font-family: Calibri, sans-serif; font-size: 11pt; line-height: 1.6; margin: 1in; }
        h1 { font-size: 18pt; color: #1a1a1a; margin-bottom: 4pt; }
        .meta { font-size: 9pt; color: #888; margin-bottom: 16pt; }
        .content { white-space: pre-wrap; }
        .footer { font-size: 8pt; color: #aaa; margin-top: 24pt; border-top: 1px solid #ddd; padding-top: 8pt; }
      </style>
    </head>
    <body>
      <h1>Axiom</h1>
      <div class="meta">axiom-solver.com · ${new Date().toLocaleDateString()}</div>
      <div class="content">${text.replace(/\n/g, "<br>")}</div>
      <div class="footer">Generated by Axiom</div>
    </body>
    </html>
  `;

  const blob = new Blob([htmlContent], {
    type: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  });

  const link = document.createElement("a");
  link.href = URL.createObjectURL(blob);
  link.download = `${filename}.doc`;
  link.click();
  URL.revokeObjectURL(link.href);
}
