import Link from 'next/link';

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[var(--color-bg0)] text-[var(--color-text-primary)] py-24 px-5">
      <div className="max-w-2xl mx-auto">
        <Link href="/" className="text-sm text-[var(--color-text-secondary)] hover:text-[var(--color-text-primary)] mb-8 inline-block">&larr; Back to home</Link>
        <h1 className="text-4xl font-extrabold mb-8">Terms of Service</h1>
        <div className="space-y-6 text-[var(--color-text-secondary)] leading-relaxed">
          <p><strong className="text-[var(--color-text-primary)]">Last updated:</strong> February 2026</p>

          <h2 className="text-xl font-bold text-[var(--color-text-primary)] mt-8">1. Acceptance of Terms</h2>
          <p>By accessing or using Axiom, you agree to be bound by these Terms of Service. If you do not agree, please do not use the service.</p>

          <h2 className="text-xl font-bold text-[var(--color-text-primary)] mt-8">2. Description of Service</h2>
          <p>Axiom is an AI-powered study companion that provides homework solutions, essay writing assistance, text humanization, and exam preparation tools. Responses are generated by AI and should be used as a learning aid, not submitted as your own work.</p>

          <h2 className="text-xl font-bold text-[var(--color-text-primary)] mt-8">3. User Accounts</h2>
          <p>You are responsible for maintaining the security of your account credentials. You must be at least 13 years old to use this service.</p>

          <h2 className="text-xl font-bold text-[var(--color-text-primary)] mt-8">4. Subscription &amp; Billing</h2>
          <p>Pro subscriptions are billed monthly at $9.99/month. You can cancel at any time through the Settings page. Refunds are handled on a case-by-case basis.</p>

          <h2 className="text-xl font-bold text-[var(--color-text-primary)] mt-8">5. Acceptable Use</h2>
          <p>You agree not to use Axiom for any illegal purposes, to harass others, or to attempt to circumvent rate limits or security measures.</p>

          <h2 className="text-xl font-bold text-[var(--color-text-primary)] mt-8">6. Disclaimer</h2>
          <p>AI-generated content may contain errors. Axiom is provided &ldquo;as is&rdquo; without warranties of any kind. We are not responsible for academic consequences resulting from the use of our service.</p>

          <h2 className="text-xl font-bold text-[var(--color-text-primary)] mt-8">7. Contact</h2>
          <p>For questions about these terms, contact us at <a href="mailto:support@axiom.study" className="text-emerald-400 hover:underline">support@axiom.study</a>.</p>
        </div>
      </div>
    </div>
  );
}
